[package]
name = "ImageEffects"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.80"
base64 = "0.13.0"
image = "0.23.14"

[dependencies.web-sys]
version = "0.3.4"
features = ["console"]